### ISSUE TITLE
რაღაც პრობლემა

### ISSUE THREAD

**Issue by varsimashvili22** [NinoPapava11/test_4_group#1]
მაქვს პრობლემა ამა და ამ ფაილში

**Comment by varsimashvili22** [comment]
აქ შეგვიძლია ჩვენ პრობლემაზე ვილაპარაკოთ

**Comment by zazamirotadze** [comment]
> აქ შეგვიძლია ჩვენ პრობლემაზე ვილაპარაკოთ

**საინტერესო** ### _პრობლემაა_ 

> 324325 @varsimashvili22  #google

**Comment by NinoPapava11** [comment]
### _**კომენტარი**_

**Comment by varsimashvili22** [comment]
გასწორდა ეს პრობლემა
